spring:
  datasource:
    url: jdbc:mysql://211.188.49.39:3306/neulbom?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: Qkrehdwns1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 50
        one-indexed-parameters: true
  session:
    timeout: 1800
  security:
    csrf:
      enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true # <- data.sql? ???? Hibernate? ?? ??? ???? ???? true? ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000 #??? ??
        #       ???? sql??? ??? sql ?? ??? ??? ???
        show_sql: true #sql ?? ????
        format_sql: true  #sql ??? ??
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

    #OSIV ?? ??
    open-in-view: false

  cloud:
    ncp:
      credentials:
        access-key: ncp_iam_BPAMKR3qYNVRg4YGytcq
        secret-key: ncp_iam_BPKMKRa7zUTkVgT41f8wrdKHZ7EaBKoOGJ
      region:
        static: kr-standard  # Korea Standard Region
      stack:
        auto: false

      # Object Storage 설정
      objectstorage:
        endpoint: https://kr.object.ncloudstorage.com
        bucket: neulbom-bucket
        access-key: ncp_iam_BPAMKR3qYNVRg4YGytcq
        secret-key: ncp_iam_BPKMKRa7zUTkVgT41f8wrdKHZ7EaBKoOGJ

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    session:
      timeout : 30m
      cookie:
        same-site: none
        max-age: 1800  # 세션 유효 시간 (초)

