spring.application.name=neulbom
# MySQL ?????? ?? ??
spring.datasource.url=jdbc:mysql://:3306/neulbom?serverTimezone=UTC
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ?? (??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
