spring.application.name=neulbom
# MySQL ?????? ?? ??
spring.datasource.url=jdbc:mysql://43.203.205.147:3306/neulbom?serverTimezone=UTC
spring.datasource.username=dj
spring.datasource.password=Qkrehd1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ?? (??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
